language: objective-c
osx_image: xcode11

script:
    - xcodebuild test -scheme SwiftKeychainWrapper -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE,OS=12.1"
#    - xcodebuild test -scheme SwiftKeychainWrapper -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV,OS=12.1"
